### ISSUE TITLE
Reconsider R Class names (and struct names in Rust)?

### ISSUE THREAD

**Issue by eitsupi** [yutannihilation/datafusionr#3]
I don't know if this applies here, but early in the development of the `polars` package there was a class name conflict with the `arrow` package (pola-rs/r-polars#11).

So I always prefix class names with the package name...

**Comment by yutannihilation** [comment]
Which one do you mean in particular? `RDataFrame` is not unique enough? Or, is this a problem I will face in future, not now?

**Comment by eitsupi** [comment]
> Which one do you mean in particular? `RDataFrame` is not unique enough? Or, is this a problem I will face in future, not now?

Of course, it's not a problem right now, but rather a potential problem in the future - RDataFrame and RExpr could be chosen to create bindings for things like Polars or DataFusion, in which case they would conflict.

**Comment by yutannihilation** [comment]
Thanks, noted. Okay, let's choose redundant names.
